CREATE TABLE USER(
   USER_ID INT AUTO_INCREMENT PRIMARY KEY,
   USER_EMAIL VARCHAR(30) NOT NULL,
   USER_NAME VARCHAR(20),
   USER_PASS VARCHAR(30),
   USER_AGE INT,
   USER_ROLE VARCHAR(10),
   REGISTER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
   USER_IMAGE VARCHAR(50)
);