CREATE TABLE USER(
   USER_ID VARCHAR(20) PRIMARY KEY NOT NULL,
   USER_NAME VARCHAR(20),
   USER_PASS varchar(30),
   USER_AGE INT,
   USER_ROLE varchar(10),
   REGISTER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);